In [1]:
import tensorflow as tf
from tqdm import tqdm
import cv2
import mediapipe as mp
import numpy as np

In [2]:
model = tf.keras.models.load_model('signs_model_efficientnetv2-s')

In [3]:
model

In [4]:
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

In [5]:
# For webcam input:
cap = cv2.VideoCapture(0)
success, image = cap.read()

In [6]:
print('Original Dimensions : ',image.shape)
 
width = model.input_shape[1]
height = model.input_shape[2] # keep original height
dim = (width, height)
  
# resize image
resized = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)
 
cv2.imshow("Resized image", resized)

Original Dimensions :  (480, 640, 3)
Resized Dimensions :  (384, 384, 3)


In [7]:
class_names =["Opaque", "Red", "Green"]

In [8]:
width = model.input_shape[1]
height = model.input_shape[2] # keep original height
dim = (width, height)
  
# resize image
resized = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
prediction_scores = model.predict(np.expand_dims(resized, axis=0))
predicted_index = np.argmax(prediction_scores)
print("Predicted label: " + class_names[predicted_index])

Predicted label: Red


In [14]:
predictions = []
frames_to_rolling_mean = 30

In [17]:
class_predicted = class_names[predicted_index]
predictions.append(prediction_scores)
rolling_mean_prediction = np.mean(predictions[-frames_to_rolling_mean:], axis=0)

In [18]:
rolling_mean_prediction

array([[  8.297888, 152.98824 ,  72.04376 ]], dtype=float32)

In [19]:
predicted_index = np.argmax(rolling_mean_prediction)

In [20]:
predicted_index

1

In [21]:
class_predicted = class_names[predicted_index]


In [24]:
rolling_mean_prediction[0]

array([  8.297888, 152.98824 ,  72.04376 ], dtype=float32)

In [22]:
max_pred = rolling_mean_prediction[predicted_index]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [16]:

print(max_pred)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [10]:
predictions = []

In [40]:
predictions.append([0,0,0])

In [41]:
predictions

[array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 [0, 0, 0]]

In [38]:
predictions.append(prediction_scores)

In [42]:
predictions

[array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 [0, 0, 0]]

In [43]:
np.mean(predictions[-5:], axis=0)

C:\Users\lucas\anaconda3\envs\signem\lib\site-packages\numpy\core\_methods.py:163: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asanyarray(a)


array([[  6.74149323, 122.6668335 ,  57.49817505]])

In [9]:
prediction_scores

array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32)

In [10]:
with mp_hands.Hands(
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image = np.zeros(image.shape)

    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                image,
                hand_landmarks,
                mp_hands.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())

In [1]:
cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))

NameError: name 'cv2' is not defined

In [5]:
# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    success, image = cap.read()
    if not success:
        print("Ignoring empty camera frame.")
        # If loading a video, use 'break' instead of 'continue'.
        continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image = np.zeros(image.shape)

    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                image,
                hand_landmarks,
                mp_hands.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())



SyntaxError: 'continue' not properly in loop (3787763078.py, line 11)

In [2]:

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    while cap.isOpened():
        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            # If loading a video, use 'break' instead of 'continue'.
            continue

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(image)

        # Draw the hand annotations on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        image = np.zeros(image.shape)

        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image,
                    hand_landmarks,
                    mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style())

        
        # Flip the image horizontally for a selfie-view display.
        cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
        if cv2.waitKey(1) == ord('q'):
            break
cap.release()


In [4]:
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

In [5]:
# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
    model_complexity=0,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as hands:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(
            image,
            hand_landmarks,
            mp_hands.HAND_CONNECTIONS,
            mp_drawing_styles.get_default_hand_landmarks_style(),
            mp_drawing_styles.get_default_hand_connections_style())
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()

In [10]:
# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(model_complexity=0,
                    min_detection_confidence=0.5,
                    min_tracking_confidence=0.5) as hands:
    while cap.isOpened():
        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            # If loading a video, use 'break' instead of 'continue'.
            continue
        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(image)

        # Draw the hand annotations on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                                    image,
                                    hand_landmarks,
                                    mp_hands.HAND_CONNECTIONS,
                                    mp_drawing_styles.get_default_hand_landmarks_style(),
                                    mp_drawing_styles.get_default_hand_connections_style())
        # Flip the image horizontally for a selfie-view display.
        cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
        if cv2.waitKey(1) == ord('q'):
            break
cap.release()

KeyboardInterrupt: 

In [27]:
# Initialize the webcam for Hand Gesture Recognition Python project
cap = cv2.VideoCapture(0)

while True:
    # Read each frame from the webcam
    _, frame = cap.read()
    x , y, c = frame.shape

    # Flip the frame vertically
    #frame = cv2.flip(frame, 1)
    #frame.flags.writeable = False
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = hands.process(frame)
    frame.flags.writeable = True
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                frame,
                hand_landmarks,
                mp_hands.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())

    # Show the final output
    cv2.imshow("Output", cv2.flip(frame, 1))
    if cv2.waitKey(1) == ord('q'):
        break

# release the webcam and destroy all active windows
cap.release()
cv2.destroyAllWindows()

AttributeError: 'Hands' object has no attribute 'HAND_CONNECTIONS'

In [7]:
path_videos = ""
path_model = "trained_models/signs_model_efficientnetv2-s"

In [2]:
model_sings = tf.saved_model.load(path_model)

In [ ]:

path_videos = os.path.abspath(path_videos)

os.chdir(path_videos)
gestures = os.listdir(os.getcwd())

In [11]:
# Initialize the webcam for Hand Gesture Recognition Python project
cap = cv2.VideoCapture(0)

while True:
    # Read each frame from the webcam
    _, frame = cap.read()
    x , y, c = frame.shape

    # Flip the frame vertically
    #frame = cv2.flip(frame, 1)
    frame = hs.handsegment(frame)
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Show the final output
    cv2.imshow("Output", frame)
    if cv2.waitKey(1) == ord('q'):
        break

# release the webcam and destroy all active windows
cap.release()
cv2.destroyAllWindows()