In [1]:
import tensorflow as tf
from tqdm import tqdm
import cv2
import mediapipe as mp
import numpy as np

In [3]:
model = tf.keras.models.load_model('../trained_models/signs_model_efficientnetv2-s_v0')

In [5]:
lite_model_path = "../trained_models/signs_model_efficientnetv2-s_v0.tflite"

In [46]:
class_names =["Sweet milk", "Argentina", "Barbecue", "Thanks"]
frames_to_rolling_mean = 10
predictions = []
font = cv2.FONT_HERSHEY_SIMPLEX
bottomLeftCornerOfText = (10,500)
fontScale = 1
fontColor = (255,255,255)
thickness = 1
lineType = 2

In [27]:
interpreter = tf.lite.Interpreter(lite_model_path)


In [28]:
interpreter.allocate_tensors()

In [29]:
# Get input and output tensors.
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)

interpreter.invoke()

# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)


[[ 0.15329695  1.0730786   0.40879187 -1.4307716 ]]


In [36]:
def load_model(lite_model_path):
    interpreter = tf.lite.Interpreter(lite_model_path)
    interpreter.allocate_tensors()

    return interpreter


model = load_model(lite_model_path)
# Get input and output tensors.
input_details = model.get_input_details()
output_details = model.get_output_details()

# Test the model on random input data.
input_shape = input_details[0]['shape']


width = input_shape[1]
height = input_shape[2]
dim = (width, height)


In [37]:
image.shape

(480, 640, 3)

In [38]:
resized = cv2.resize(image, dim, interpolation=cv2.INTER_AREA)

In [40]:
input_data = np.expand_dims(np.array(resized, dtype=np.float32), axis=0)

In [41]:
model.set_tensor(input_details[0]['index'], input_data)

In [42]:
model.invoke()

In [43]:
# The function `get_tensor()` returns a copy of the tensor data.
# Use `tensor()` in order to get a pointer to the tensor.
prediction_scores = model.get_tensor(output_details[0]['index'])

In [44]:
prediction_scores

array([[ 1.0475292,  0.5876383, -0.7153858, -0.6642868]], dtype=float32)

In [47]:
#prediction_scores = model.predict(np.expand_dims(resized, axis=0))
predicted_index = np.argmax(prediction_scores)
class_predicted = class_names[predicted_index]
predictions.append(prediction_scores)
rolling_mean_prediction = np.mean(predictions[-frames_to_rolling_mean:], axis=0)
predicted_index = np.argmax(rolling_mean_prediction)
class_predicted = class_names[predicted_index]
max_pred = rolling_mean_prediction[0][predicted_index]

In [51]:
model.get_tensor(output_details[0]['index'])

array([[ 1.0475292,  0.5876383, -0.7153858, -0.6642868]], dtype=float32)

In [50]:
output_details[0]['index']

846

In [48]:
max_pred

1.0475292

In [ ]:


        

        # The function `get_tensor()` returns a copy of the tensor data.
        # Use `tensor()` in order to get a pointer to the tensor.
        prediction_scores = model.get_tensor(output_details[0]['index'])

        #prediction_scores = model.predict(np.expand_dims(resized, axis=0))
        predicted_index = np.argmax(prediction_scores)
        class_predicted = class_names[predicted_index]
        predictions.append(prediction_scores)
        rolling_mean_prediction = np.mean(predictions[-frames_to_rolling_mean:], axis=0)
        predicted_index = np.argmax(rolling_mean_prediction)
        class_predicted = class_names[predicted_index]
        max_pred = rolling_mean_prediction[0][predicted_index]
        if max_pred>0.1:
            cv2.putText(frame, class_predicted, (10, 50), cv2.FONT_HERSHEY_SIMPLEX,
                        1, (0, 0, 255), 2, cv2.LINE_AA)

In [10]:
interpreter.get_input_details()

[{'name': 'serving_default_input_1:0',
  'index': 0,
  'shape': array([  1, 384, 384,   3]),
  'shape_signature': array([ -1, 384, 384,   3]),
  'dtype': numpy.float32,
  'quantization': (0.0, 0),
  'quantization_parameters': {'scales': array([], dtype=float32),
   'zero_points': array([], dtype=int32),
   'quantized_dimension': 0},
  'sparsity_parameters': {}}]

In [11]:
my_signature = interpreter.get_signature_runner()


In [18]:
dim_input_data = interpreter.get_input_details()[0]["shape"]

In [20]:
input_data = np.zeros(dim_input_data)

In [25]:
my_signature.predict()

AttributeError: 'SignatureRunner' object has no attribute 'predict'

In [23]:
output = my_signature(x=tf.constant(np.zeros(dim_input_data), shape=dim_input_data, dtype=tf.float32))

ValueError: Invalid Input name (x) for SignatureDef

In [21]:
my_signature(input_data)

TypeError: __call__() takes 1 positional argument but 2 were given

In [ ]:

# my_signature is callable with input as arguments.
output = my_signature(x=tf.constant([1.0], shape=(1,10), dtype=tf.float32))
# 'output' is dictionary with all outputs from the inference.
# In this case we have single output 'result'.
print(output['result'])


In [ ]:
# interpreter = tf.lite.Interpreter(model_content=lite_model_content)
# This little helper wraps the TFLite Interpreter as a numpy-to-numpy function.
def lite_model(images):
    interpreter.allocate_tensors()
    interpreter.set_tensor(interpreter.get_input_details()[0]['index'], images)
    interpreter.invoke()
    return interpreter.get_tensor(interpreter.get_output_details()[0]['index'])

In [ ]:
  probs_lite = lite_model(image[None, ...])[0]


In [3]:
model

In [4]:
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

In [30]:
# For webcam input:
cap = cv2.VideoCapture(0)
success, image = cap.read()

array([[[133, 152, 167],
        [134, 153, 168],
        [134, 153, 168],
        ...,
        [ 85, 103, 114],
        [ 85, 103, 114],
        [ 85, 103, 114]],

       [[133, 152, 167],
        [134, 153, 168],
        [134, 153, 168],
        ...,
        [ 85, 103, 114],
        [ 85, 103, 114],
        [ 85, 103, 114]],

       [[133, 152, 167],
        [134, 153, 168],
        [134, 153, 168],
        ...,
        [ 85, 103, 114],
        [ 85, 103, 114],
        [ 85, 103, 114]],

       ...,

       [[129, 149, 166],
        [129, 149, 166],
        [129, 149, 166],
        ...,
        [197, 217, 234],
        [200, 220, 237],
        [203, 223, 240]],

       [[129, 149, 166],
        [129, 149, 166],
        [129, 149, 166],
        ...,
        [194, 214, 231],
        [196, 216, 233],
        [199, 219, 236]],

       [[129, 149, 166],
        [129, 149, 166],
        [129, 149, 166],
        ...,
        [191, 211, 228],
        [194, 214, 231],
        [196, 216, 233]]

In [6]:
print('Original Dimensions : ',image.shape)
 
width = model.input_shape[1]
height = model.input_shape[2] # keep original height
dim = (width, height)
  
# resize image
resized = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
 
print('Resized Dimensions : ',resized.shape)
 
cv2.imshow("Resized image", resized)

Original Dimensions :  (480, 640, 3)
Resized Dimensions :  (384, 384, 3)


In [7]:
class_names =["Opaque", "Red", "Green"]

In [8]:
width = model.input_shape[1]
height = model.input_shape[2] # keep original height
dim = (width, height)
  
# resize image
resized = cv2.resize(image, dim, interpolation = cv2.INTER_AREA)
prediction_scores = model.predict(np.expand_dims(resized, axis=0))
predicted_index = np.argmax(prediction_scores)
print("Predicted label: " + class_names[predicted_index])

Predicted label: Red


In [14]:
predictions = []
frames_to_rolling_mean = 30

In [17]:
class_predicted = class_names[predicted_index]
predictions.append(prediction_scores)
rolling_mean_prediction = np.mean(predictions[-frames_to_rolling_mean:], axis=0)

In [18]:
rolling_mean_prediction

array([[  8.297888, 152.98824 ,  72.04376 ]], dtype=float32)

In [19]:
predicted_index = np.argmax(rolling_mean_prediction)

In [20]:
predicted_index

1

In [21]:
class_predicted = class_names[predicted_index]


In [24]:
rolling_mean_prediction[0]

array([  8.297888, 152.98824 ,  72.04376 ], dtype=float32)

In [22]:
max_pred = rolling_mean_prediction[predicted_index]


IndexError: index 1 is out of bounds for axis 0 with size 1

In [16]:

print(max_pred)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [10]:
predictions = []

In [40]:
predictions.append([0,0,0])

In [41]:
predictions

[array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 [0, 0, 0]]

In [38]:
predictions.append(prediction_scores)

In [42]:
predictions

[array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32),
 [0, 0, 0]]

In [43]:
np.mean(predictions[-5:], axis=0)

C:\Users\lucas\anaconda3\envs\signem\lib\site-packages\numpy\core\_methods.py:163: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr = asanyarray(a)


array([[  6.74149323, 122.6668335 ,  57.49817505]])

In [9]:
prediction_scores

array([[  8.426867, 153.33354 ,  71.87272 ]], dtype=float32)

In [10]:
with mp_hands.Hands(
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image = np.zeros(image.shape)

    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                image,
                hand_landmarks,
                mp_hands.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())

In [1]:
cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))

NameError: name 'cv2' is not defined

In [5]:
# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    success, image = cap.read()
    if not success:
        print("Ignoring empty camera frame.")
        # If loading a video, use 'break' instead of 'continue'.
        continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    image = np.zeros(image.shape)

    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                image,
                hand_landmarks,
                mp_hands.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())



SyntaxError: 'continue' not properly in loop (3787763078.py, line 11)

In [2]:

mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
        model_complexity=1,
        min_detection_confidence=0.5,
        min_tracking_confidence=0.5) as hands:
    while cap.isOpened():
        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            # If loading a video, use 'break' instead of 'continue'.
            continue

        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(image)

        # Draw the hand annotations on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        image = np.zeros(image.shape)

        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                    image,
                    hand_landmarks,
                    mp_hands.HAND_CONNECTIONS,
                    mp_drawing_styles.get_default_hand_landmarks_style(),
                    mp_drawing_styles.get_default_hand_connections_style())

        
        # Flip the image horizontally for a selfie-view display.
        cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
        if cv2.waitKey(1) == ord('q'):
            break
cap.release()


In [4]:
mp_drawing = mp.solutions.drawing_utils
mp_drawing_styles = mp.solutions.drawing_styles
mp_hands = mp.solutions.hands

In [5]:
# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(
    model_complexity=0,
    min_detection_confidence=0.5,
    min_tracking_confidence=0.5) as hands:
  while cap.isOpened():
    success, image = cap.read()
    if not success:
      print("Ignoring empty camera frame.")
      # If loading a video, use 'break' instead of 'continue'.
      continue

    # To improve performance, optionally mark the image as not writeable to
    # pass by reference.
    image.flags.writeable = False
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    results = hands.process(image)

    # Draw the hand annotations on the image.
    image.flags.writeable = True
    image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
      for hand_landmarks in results.multi_hand_landmarks:
        mp_drawing.draw_landmarks(
            image,
            hand_landmarks,
            mp_hands.HAND_CONNECTIONS,
            mp_drawing_styles.get_default_hand_landmarks_style(),
            mp_drawing_styles.get_default_hand_connections_style())
    # Flip the image horizontally for a selfie-view display.
    cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
    if cv2.waitKey(5) & 0xFF == 27:
      break
cap.release()

In [10]:
# For webcam input:
cap = cv2.VideoCapture(0)
with mp_hands.Hands(model_complexity=0,
                    min_detection_confidence=0.5,
                    min_tracking_confidence=0.5) as hands:
    while cap.isOpened():
        success, image = cap.read()
        if not success:
            print("Ignoring empty camera frame.")
            # If loading a video, use 'break' instead of 'continue'.
            continue
        # To improve performance, optionally mark the image as not writeable to
        # pass by reference.
        image.flags.writeable = False
        image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        results = hands.process(image)

        # Draw the hand annotations on the image.
        image.flags.writeable = True
        image = cv2.cvtColor(image, cv2.COLOR_RGB2BGR)
        if results.multi_hand_landmarks:
            for hand_landmarks in results.multi_hand_landmarks:
                mp_drawing.draw_landmarks(
                                    image,
                                    hand_landmarks,
                                    mp_hands.HAND_CONNECTIONS,
                                    mp_drawing_styles.get_default_hand_landmarks_style(),
                                    mp_drawing_styles.get_default_hand_connections_style())
        # Flip the image horizontally for a selfie-view display.
        cv2.imshow('MediaPipe Hands', cv2.flip(image, 1))
        if cv2.waitKey(1) == ord('q'):
            break
cap.release()

KeyboardInterrupt: 

In [27]:
# Initialize the webcam for Hand Gesture Recognition Python project
cap = cv2.VideoCapture(0)

while True:
    # Read each frame from the webcam
    _, frame = cap.read()
    x , y, c = frame.shape

    # Flip the frame vertically
    #frame = cv2.flip(frame, 1)
    #frame.flags.writeable = False
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
    results = hands.process(frame)
    frame.flags.writeable = True
    frame = cv2.cvtColor(frame, cv2.COLOR_RGB2BGR)
    if results.multi_hand_landmarks:
        for hand_landmarks in results.multi_hand_landmarks:
            mp_drawing.draw_landmarks(
                frame,
                hand_landmarks,
                mp_hands.HAND_CONNECTIONS,
                mp_drawing_styles.get_default_hand_landmarks_style(),
                mp_drawing_styles.get_default_hand_connections_style())

    # Show the final output
    cv2.imshow("Output", cv2.flip(frame, 1))
    if cv2.waitKey(1) == ord('q'):
        break

# release the webcam and destroy all active windows
cap.release()
cv2.destroyAllWindows()

AttributeError: 'Hands' object has no attribute 'HAND_CONNECTIONS'

In [7]:
path_videos = ""
path_model = "trained_models/signs_model_efficientnetv2-s"

In [2]:
model_sings = tf.saved_model.load(path_model)

In [ ]:

path_videos = os.path.abspath(path_videos)

os.chdir(path_videos)
gestures = os.listdir(os.getcwd())

In [11]:
# Initialize the webcam for Hand Gesture Recognition Python project
cap = cv2.VideoCapture(0)

while True:
    # Read each frame from the webcam
    _, frame = cap.read()
    x , y, c = frame.shape

    # Flip the frame vertically
    #frame = cv2.flip(frame, 1)
    frame = hs.handsegment(frame)
    frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    # Show the final output
    cv2.imshow("Output", frame)
    if cv2.waitKey(1) == ord('q'):
        break

# release the webcam and destroy all active windows
cap.release()
cv2.destroyAllWindows()